CREATE TABLE CITY(
ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
NAME VARCHAR(30) NOT NULL UNIQUE,
POPULATION INT NOT NULL,
LATITUDE DECFLOAT NOT NULL,
LONGITUDE DECFLOAT NOT NULL
);

CREATE TABLE REGION(
ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
NAME VARCHAR(30) NOT NULL
);

CREATE TABLE PROVINCE(
ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
NAME VARCHAR(30) NOT NULL,
ACRONYM VARCHAR(2) NOT NULL
);

CREATE TABLE MUNICIPALITY(
ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
NAME VARCHAR(40) NOT NULL,
RESIDENT_NUMBER INT NOT NULL,
REGION_ID BIGINT NOT NULL,
PROVINCE_ID BIGINT NOT NULL,
LATITUDE DECFLOAT NOT NULL,
LONGITUDE DECFLOAT NOT NULL,
FOREIGN KEY(REGION_ID) REFERENCES REGION(ID),
FOREIGN KEY(PROVINCE_ID) REFERENCES PROVINCE(ID)
);